services:
  dvc-runner:
    build: .
    volumes:
      - .:/workspace
      - dvc-cache:/workspace/.dvc/cache
      # Optional: Mount credentials if needed for dvc push/pull later
      # - ~/.aws:/root/.aws:ro
      # - ~/.ssh:/root/.ssh:ro
    working_dir: /workspace
    environment:
      # === ADD DAGSHUB CREDENTIALS HERE ===
      # Get these from DagsHub: Repo -> Remote Button -> Experiment Tracking Tab
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - DAGSHUB_USER_TOKEN=${DAGSHUB_USER_TOKEN}
      # Optional: Set if your repo name/owner differ from the logged-in user
      # - DAGSHUB_USER_TOKEN=${DAGSHUB_USER_TOKEN} # Alternative authentication
      # - DAGSHUB_REPO_OWNER=YOUR_DAGSHUB_USERNAME
      # - DAGSHUB_REPO_NAME=YOUR_REPO_NAME

volumes:
  dvc-cache: